### ISSUE TITLE
What should happen the .stack getter is invoked on non-error instances

### ISSUE THREAD

**Issue by evilpie** [ljharb/proposal-error-stacks#3]
There is some evidence that having Error#stack throw for non error instances is web incompatible.
- We can imagine some weird iteration code touching Error.prototype.stack
- Naive pre-ES6 subclassing of Errors always end up as non Error instances. Consider this highly voted StackOverflow example: https://stackoverflow.com/questions/783818/how-do-i-create-a-custom-error-in-javascript

This came up while I was changing Error.prototype to an ordinary object in Firefox [bug 1213341](https://bugzilla.mozilla.org/show_bug.cgi?id=1213341).
It looks like v8 is generally not affected by this because they define stack on every new error instance.

**Comment by erights** [comment]
We could have the `Error.prototype.stack` getter not throw but have `System.getStack` throw. There was no strong reason for the getter and `System.getStack` to have precisely the same behavior; it was just that there was no reason not to. Now there is.

**Comment by ljharb** [comment]
That sounds perfectly reasonable

**Comment by ljharb** [comment]
@erights in the case where the getter is `.call`ed on a non-Error object, what should it return?

**Comment by erights** [comment]
`undefined`

**Comment by evilpie** [comment]
Wait, how did you decide on `undefined`? I cited multiple examples that result in `""` (empty string), i.e. the stackoverflow question.

**Comment by ljharb** [comment]
@evilpie in that SO code I see a lot of `|| ''` which seems like it'd work with `undefined`, but it's a long post so it's hard to distill out the compat details.

Can you elaborate on why `undefined` wouldn't be compatible, or why returning the empty string would be better?
