### ISSUE TITLE
Outdated V8 information

### ISSUE THREAD

**Issue by farsightsoftware** [ljharb/proposal-error-stacks#4]
The current proposal language says under **Compatibility**:

> node/Chrome: stack is an own property on Error instances with a getter/setter: `{ configurable: true, enumerable: false }`

This is incorrect. The descriptor returned is:

    {"value":"(stack here)","writable":true,"enumerable":false,"configurable":true}

...but V8's `Error` has exotic behavior for [[GetOwnProperty]] that acts like a getter the first time (if there's been no intervening set) by triggering `prepareStackTrace` and setting `stack`, as discussed in [this thread](https://esdiscuss.org/topic/getownpropertydescriptor-side-effects). After that, it behaves like a standard value property.

**Comment by ljharb** [comment]
Short of the observable `prepareStackTrace` call, can that exotic behavior be observed?

**Comment by farsightsoftware** [comment]
As far as I know, doing something with `prepareStackTrace` is the only way to observe it, but basically all I know of it is from that thread. But it being a value property means that you can't get the getter/setter and apply them to another object (such as a non-`Error` object), since what you get back from `getOwnPropertyDesciptor` has `value`, not `get`/`set`.

**Comment by ljharb** [comment]
Right - it's a value property always, because there's no observable getter.

**Comment by farsightsoftware** [comment]
Just documenting here that @ljharb found that the old text is correct for older versions of V8, specifically he found that Chrome 53 has the old text's behavior and Chrome 54 the new text's. I'd only checked Node 7, and sure enough, Node 6 has the old text's behavior as well. Amended the PR to keep the old text and just identify versions.

**Comment by ljharb** [comment]
Closed in #5
